=begin
#Assessment Network Interactions API

#> Records interactions with content distributed by the Assessment Network  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `...a15k.org/v0/flags`. While the API does support a default version, that version will change over time and therefore should not be used in production code!  Some endpoints require an API key to be passed in the request header.  There are two types of API keys: API tokens and API IDs.  An API token is used for more restricted access.  Such tokens should not be shared with end users.  API IDs are used for less restricted access and may be exposed to clients (e.g. through use in browser-side code).  Both keys are available to members through www.a15k.org. 

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for A15kInteractions::FlagsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FlagsApi' do
  before do
    # run before each test
    @instance = A15kInteractions::FlagsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FlagsApi' do
    it 'should create an instance of FlagsApi' do
      expect(@instance).to be_instance_of(A15kInteractions::FlagsApi)
    end
  end

  # unit tests for create_flag
  # Flag some content
  # Adds a flag to some content for some user in some app.
  # @param flag The flag data
  # @param [Hash] opts the optional parameters
  # @return [Flag]
  describe 'create_flag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_flag
  # Delete a flag
  # Delete a flag.  Anyone with the flag ID (very hard to guess) can delete it.
  # @param id ID of the flag to delete
  # @param [Hash] opts the optional parameters
  # @return [Flag]
  describe 'delete_flag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_flag
  # Retrieve a flag
  # Retrieve a flag.  Anyone with the flag ID (very hard to guess) can retrieve it.
  # @param id ID of the flag to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Flag]
  describe 'get_flag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_flag
  # Update a flag
  # Update a flag with the provided values.
  # @param id ID of the flag
  # @param [Hash] opts the optional parameters
  # @option opts [Flag] :flag The flag data
  # @return [Flag]
  describe 'update_flag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
