=begin
#Assessment Network Interactions API

#Records interactions with content distributed by the Assessment Network.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `...a15k.org/v0/flags`.          While the API does support a default version, that version will change over          time and therefore should not be used in production code!  Some endpoints require an API key to be passed in the request header.  There are two          types of API keys: API tokens and API IDs.  An API token is used for more restricted          access.  Such tokens should not be shared with end users.  API IDs are used for less          restricted access and may be exposed to clients (e.g. through use in browser-side code).          Both keys are available to members through www.a15k.org. 

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for A15kInteractions::RatingsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RatingsApi' do
  before do
    # run before each test
    @instance = A15kInteractions::RatingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RatingsApi' do
    it 'should create an instance of RatingsApi' do
      expect(@instance).to be_instance_of(A15kInteractions::RatingsApi)
    end
  end

  # unit tests for create_rating
  # Rate some content
  # Rates some content for some user in some app.  New ratings replace old ratings.
  # @param rating The rating data
  # @param [Hash] opts the optional parameters
  # @return [Rating]
  describe 'create_rating test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_rating
  # Delete a rating
  # Delete a rating.  Anyone with the rating ID (very hard to guess) can delete it.
  # @param id ID of the rating to delete
  # @param [Hash] opts the optional parameters
  # @return [Flag]
  describe 'delete_rating test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_rating
  # Retrieve a rating
  # Retrieve a rating.  Anyone with the rating ID (very hard to guess) can retrieve it.
  # @param id ID of the rating to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Rating]
  describe 'get_rating test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
