dist: trusty
sudo: false
language: ruby
rvm: 2.5.0
cache: bundler
branches:
  only:
    - master
before_install:
  - nvm install 8
  - cd clients/0.1.0/javascript ; npm install
script:
  - bundle exec rake
