=begin
#Assessment Network Interactions API

#Records interactions with content distributed by the Assessment Network.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `...a15k.org/v0/flags`.          While the API does support a default version, that version will change over          time and therefore should not be used in production code!  Some endpoints require an API key to be passed in the request header.  There are two          types of API keys: API tokens and API IDs.  An API token is used for more restricted          access.  Such tokens should not be shared with end users.  API IDs are used for less          restricted access and may be exposed to clients (e.g. through use in browser-side code).          Both keys are available to members through www.a15k.org. 

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'a15k_interactions_api/api_client'
require 'a15k_interactions_api/api_error'
require 'a15k_interactions_api/version'
require 'a15k_interactions_api/configuration'

# Models
require 'a15k_interactions_api/models/app'
require 'a15k_interactions_api/models/app_update'
require 'a15k_interactions_api/models/error'
require 'a15k_interactions_api/models/flag'
require 'a15k_interactions_api/models/flag_new'
require 'a15k_interactions_api/models/flag_update'
require 'a15k_interactions_api/models/presentation'
require 'a15k_interactions_api/models/presentation_response'
require 'a15k_interactions_api/models/rating'
require 'a15k_interactions_api/models/rating_new'

# APIs
require 'a15k_interactions_api/api/apps_api'
require 'a15k_interactions_api/api/flags_api'
require 'a15k_interactions_api/api/presentations_api'
require 'a15k_interactions_api/api/ratings_api'

module A15kInteractions
  class << self
    # Customize default settings for the SDK using block.
    #   A15kInteractions.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
