=begin
#Assessment Network Interactions API

#Records interactions with content distributed by the Assessment Network.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `...a15k.org/v0/flags`.          While the API does support a default version, that version will change over          time and therefore should not be used in production code!  Some endpoints require an API key to be passed in the request header.  There are two          types of API keys: API tokens and API IDs.  An API token is used for more restricted          access.  Such tokens should not be shared with end users.  API IDs are used for less          restricted access and may be exposed to clients (e.g. through use in browser-side code).          Both keys are available to members through www.a15k.org. 

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require "uri"

module A15kInteractions
  class PresentationsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Indicate that content was presented
    # Called when network content is presented to any end user
    # @param presentation The presentation data
    # @param [Hash] opts the optional parameters
    # @return [PresentationResponse]
    def create_presentation(presentation, opts = {})
      data, _status_code, _headers = create_presentation_with_http_info(presentation, opts)
      return data
    end

    # Indicate that content was presented
    # Called when network content is presented to any end user
    # @param presentation The presentation data
    # @param [Hash] opts the optional parameters
    # @return [Array<(PresentationResponse, Fixnum, Hash)>] PresentationResponse data, response status code and response headers
    def create_presentation_with_http_info(presentation, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PresentationsApi.create_presentation ..."
      end
      # verify the required parameter 'presentation' is set
      if @api_client.config.client_side_validation && presentation.nil?
        fail ArgumentError, "Missing the required parameter 'presentation' when calling PresentationsApi.create_presentation"
      end
      # resource path
      local_var_path = "/presentations"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(presentation)
      auth_names = ['api_id']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'PresentationResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PresentationsApi#create_presentation\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
